[arcgis]
portal_url = https://YOUR-AGOL.maps.arcgis.com/
username = YOUR-USERNAME
password = YOUR-PASSWORD

[restore]
backup_folder = C:\temp\webmap_backups

# all | single
restore_mode = all

# Only used when restore_mode=single
# Assumes previous serviceupdater run (creates the backup)
webmap_id = YOUR-WEBMAPID

# false = log only, do not restore -- true = perform restore
dry_run = true

# processing log is written here (also contains details of restore operations performed, or that would have been performed in dry_run mode)
log_folder = C:\temp\webmap_backups