[arcgis]
portal_url = your-arcgis-online (e.g. https://myorg.maps.arcgis.com)
username = your-username
password = your-password

[restore]
backup_folder = C:\temp\webmap_backups\webmap_backups_20260408_133914

# all | single
restore_mode = all

# Only used when restore_mode=single
webmap_id = f17fe423f8ac4e7eb14069c5baa8d5f3

# false = log only, do not restore -- true = perform restore
dry_run = true

# processing log is written here (also contains details of restore operations performed, or that would have been performed in dry_run mode)
log_folder = C:\temp\webmap_backups