[arcgis]
portal_url = your-arcgis-online (e.g. https://myorg.maps.arcgis.com)
username = your-username
password = your-password

[urls]
from_url = your-from-url
to_url   = your-to-url


[search]
webmap_search_query = type:"Web Map"

[run]
#  dry_run = true -- will not save any changes to the webmap items, but will log all changes that would have been applied
#  dry_run = false -- will apply and save all changes to the webmap items
#  note: json backups are still created when dry_run=true
dry_run = true

log_folder = C:\temp

#  max_webmaps = -1 -- set to a positive integer to limit the number of webmaps processed, 
#  or -1 to process all webmaps found
max_webmaps = -1


#  enable/disable backup creation
backup_enabled = true

#  OPTIONAL: choose a dedicated backup root (otherwise it uses log_folder\webmap_backups\...)
backup_root = C:\temp\webmap_backups
