[arcgis]
portal_url = https://YOUR-AGOL.maps.arcgis.com/
username = YOUR-USERNAME
password = YOUR-PASSWORD

[urls]

# -----------------------------------------------------
# Actual client from, to urls and to itemid (to be set if the itemId is present)
# -----------------------------------------------------
from_url = YOUR-FROM-URL
to_url   = YOUR-TO-URL
# this is the portal itemid for the to_url. If the found item has a itemId property it will be set to this value
to_itemid = YOUR-TO-URL-ITEMID

[search]
# two choices available (uncomment only one per run):

# webmap_search_query = type:"Web Map" -- will search for all webmaps, and process those that have the from_url in them
#	uses: dry_run, max_matching_webmaps_to_process

# webmap_search_query = id:"YOUR-ItemID-TO-SEARCH-FOR" -- will only search for the webmap with the specified id (useful for testing)
#	uses: dry_run, max_matching_webmaps_to_process

webmap_search_query = type:"Web Map"


[run]
#  dry_run = true -- will not save any changes to the webmap items, but will log all changes that would have been applied
#  dry_run = false -- will apply and save all changes to the webmap items
#  note: json backups are still created when dry_run=true
dry_run = true

# log_folder is required, and is where processing log is written, and also where json backups are written (if backup_enabled=true)
log_folder = C:\temp

# default to processing all matching webmaps, but allow user to set a limit for testing
# example: max_matching_webmaps_to_process = 10 -- will only process the first 10 matching webmaps, then stop
# rerunning will then cause the next 10 to be processed, etc. until all matching webmaps have been processed
max_matching_webmaps_to_process = -1

#  enable/disable backup creation
backup_enabled = true

#  OPTIONAL: choose a dedicated backup root (otherwise it uses log_folder\webmap_backups\...)
backup_root = C:\temp\webmap_backups

